version: "2"
services:


  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    command: ["--collector.otlp.enabled=true"]
    ports:
      - "16686:16686"
      - "4317"
      - "4318"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.76.1
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "14268:14268"
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  application:
    build:
      dockerfile: flask.Dockerfile
    restart: always
    environment:
      - JAEGER_HOST=otel-collector
    ports:
      - "5000:5000"


