receivers:
  jaeger:
    protocols:
      grpc: 
      thrift_binary:  
      thrift_compact: 
      thrift_http: 

exporters:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  logging:
   loglevel: debug

processors:
  batch:
    timeout: 1s
  attributes:
    actions:
      - key: environment
        value: opentelemetry-seb
        action: insert

extensions:
  health_check:
  pprof:
   endpoint: :1888
  zpages:
   endpoint: :55679
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch,attributes]
      exporters: [jaeger,logging]
  
  telemetry:
    logs:
      level: "debug"
